import {
  HiOutlineTrendingUp,
  HiOutlineX,
  HiOutlineExclamation,
  HiOutlineInformationCircle,
  HiOutlineStatusOnline,
  HiOutlineBan,
} from 'react-icons/hi';

import {
  MdFitnessCenter,
  MdSportsMartialArts,
  MdDirectionsBike,
  MdSelfImprovement,
  MdSportsMma,
  MdPool,
} from 'react-icons/md';

import {
  RiDashboardLine,
  RiMoneyDollarCircleLine,
  RiCalendarEventLine,
  RiSettings3Line,
  RiStoreLine,
  RiUploadCloud2Line,
  RiImageLine,
  RiDeleteBinLine,
  RiEditLine,
  RiAddCircleLine,
  RiCheckboxCircleLine,
  RiCloseCircleLine,
  RiPhoneLine,
  RiMapPinLine,
  RiTimeLine,
  RiShieldCheckLine,
  RiGroupLine,
  RiFireLine,
  RiMedalLine,
  RiHeartPulseLine,
  RiBankCardLine,
  RiNotificationLine,
  RiLogoutBoxLine,
  RiMenuLine,
  RiSearchLine,
  RiEyeLine,
  RiLockLine,
  RiMailLine,
  RiGlobalLine,
  RiBuildingLine,
  RiArrowRightLine,
  RiArrowLeftLine,
  RiRefreshLine,
  RiDownloadLine,
  RiTrophyLine,
  RiStarLine,
  RiRunLine,
  RiFlashlightLine,
  RiSunLine,
  RiMoonLine,
} from 'react-icons/ri';

export const NavIcons = {
  Dashboard: RiDashboardLine,
  Classes: MdFitnessCenter,
  Memberships: RiBankCardLine,
  Bookings: RiCalendarEventLine,
  Earnings: RiMoneyDollarCircleLine,
  Profile: RiStoreLine,
  Settings: RiSettings3Line,
};

export const ActionIcons = {
  Add: RiAddCircleLine,
  Edit: RiEditLine,
  Delete: RiDeleteBinLine,
  Upload: RiUploadCloud2Line,
  Download: RiDownloadLine,
  Search: RiSearchLine,
  Refresh: RiRefreshLine,
  View: RiEyeLine,
  Close: HiOutlineX,
  Check: RiCheckboxCircleLine,
  Cancel: RiCloseCircleLine,
  Logout: RiLogoutBoxLine,
  Menu: RiMenuLine,
  ArrowRight: RiArrowRightLine,
  ArrowLeft: RiArrowLeftLine,
};

export const StatIcons = {
  Revenue: RiMoneyDollarCircleLine,
  Bookings: RiCalendarEventLine,
  Members: RiGroupLine,
  Classes: MdFitnessCenter,
  Fire: RiFireLine,
  Trophy: RiTrophyLine,
  Star: RiStarLine,
  Medal: RiMedalLine,
  Trending: HiOutlineTrendingUp,
  Heart: RiHeartPulseLine,
};

export const ContactIcons = {
  Phone: RiPhoneLine,
  Location: RiMapPinLine,
  Email: RiMailLine,
  Website: RiGlobalLine,
  Building: RiBuildingLine,
  Clock: RiTimeLine,
  Shield: RiShieldCheckLine,
  Lock: RiLockLine,
  Card: RiBankCardLine,
  Notification: RiNotificationLine,
};

export const FitnessIcons = {
  Gym: MdFitnessCenter,
  Yoga: MdSelfImprovement,
  Boxing: MdSportsMartialArts,
  MMA: MdSportsMma,
  Cycling: MdDirectionsBike,
  Swimming: MdPool,
  Running: RiRunLine,
  Flash: RiFlashlightLine,
  Sun: RiSunLine,
  Moon: RiMoonLine,
};

export const StatusIcons = {
  Online: HiOutlineStatusOnline,
  Offline: HiOutlineBan,
  Warning: HiOutlineExclamation,
  Info: HiOutlineInformationCircle,
  Success: RiCheckboxCircleLine,
  Error: RiCloseCircleLine,
};

export {
  RiDashboardLine as DashboardIcon,
  MdFitnessCenter as GymIcon,
  RiBankCardLine as MembershipIcon,
  RiCalendarEventLine as BookingIcon,
  RiMoneyDollarCircleLine as EarningsIcon,
  RiStoreLine as ProfileIcon,
  RiSettings3Line as SettingsIcon,
  RiAddCircleLine as AddIcon,
  RiEditLine as EditIcon,
  RiDeleteBinLine as DeleteIcon,
  RiUploadCloud2Line as UploadIcon,
  RiCheckboxCircleLine as CheckIcon,
  RiCloseCircleLine as CloseIcon,
  RiPhoneLine as PhoneIcon,
  RiMapPinLine as LocationIcon,
  RiTimeLine as TimeIcon,
  RiGroupLine as UsersIcon,
  RiMoneyDollarCircleLine as MoneyIcon,
  RiFireLine as FireIcon,
  RiShieldCheckLine as ShieldIcon,
  RiLogoutBoxLine as LogoutIcon,
  RiMenuLine as MenuIcon,
  HiOutlineTrendingUp as TrendingIcon,
  RiImageLine as ImageIcon,
};
